### ISSUE TITLE
Exception for Plug.Upload

### ISSUE THREAD

**Issue by hamann** [navinpeiris/logster#2]
This exception occurs when I try to upload something

``` iex
Server: localhost:4000 (http)
Request: POST /admin/uploads
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for %Plug.Upload{content_type: "image/png", filename: "Bildschirmfoto 2016-04-06 um 10.14.12.png", path: "/tmp/plug-1459/multipart-930459-149247-1"}
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:116: Enumerable.reduce/3
        (elixir) lib/enum.ex:1477: Enum.reduce/3
        (elixir) lib/enum.ex:1025: Enum.into/4
        (logster) lib/logster/plugs/logger.ex:68: anonymous fn/1 in Logster.Plugs.Logger.filter_params/1
        (elixir) lib/enum.ex:1019: anonymous fn/4 in Enum.into/3
        (stdlib) lists.erl:1262: :lists.foldl/3
        (elixir) lib/enum.ex:1025: Enum.into/4
```

**Comment by navinpeiris** [comment]
Wow, thanks for letting me know @hamann. I'll check it out and get a new release out that fixes this in the next hour or so

**Comment by hamann** [comment]
Thanks!
In case you need it, this test fails

``` elixir
upload = %Plug.Upload{content_type: "image/png", filename: "foo.png", path: "/tmp/plug-1234/multipart-1234-1234-1"}
{_conn, message} = conn(:post, "/hello/world", [upload: upload, foo: :bar]) |> call
```

**Comment by navinpeiris** [comment]
Awesome, thanks @hamann. Version `0.1.4` was just released that fixes this issue.

Do let me know if it is and I'll close this issue.

**Comment by hamann** [comment]
The errors with Plug.Upload are fixed, thanks a lot!

**Comment by navinpeiris** [comment]
👍
